### ISSUE TITLE
4.2.0: No route matches [GET] "/fonts/font-awesome/fontawesome-webfont.ttf"

### ISSUE THREAD

**Issue by elbarto132** [FortAwesome/font-awesome-sass#48]
When using the 4.2.0 gem i get:
ActionController::RoutingError (No route matches [GET] "/fonts/font-awesome/fontawesome-webfont.ttf"):
4.1.0 is working fine.

i saw that the location of the file changed in 4.2, probably this is the problem?
.//.rvm/gems/ruby-2.1.2/gems/font-awesome-less-4.0.2/vendor/assets/fonts/fontawesome-webfont.ttf
.//.rvm/gems/ruby-2.1.2/gems/font-awesome-sass-4.1.0/vendor/assets/fonts/fontawesome-webfont.ttf
.//.rvm/gems/ruby-2.1.2/gems/font-awesome-sass-4.2.0/assets/fonts/font-awesome/fontawesome-webfont.ttf

**Comment by reiz** [comment]
I'm having the same issue, but after adding the 2 lines I'm getting this error: 

```
File to import not found or unreadable: font-awesome-sprockets
```

Any ideas?

**Comment by JackWells** [comment]
@relz - your problem is likely that you are using the 'font-awesome-rails' gem, but those instructions are for the "'font-awesome-sass'" gem.  I made the gem-change, got rid of the error you experienced, but the underlying problem persisted - "no route matches..."  I also added the 'new feature' Rails4.x headache, noted by @nacengineer above (tried with both gem versions).  

I did get fingerprinted versions showing up in public after assets:precompile with the 'sass' version of the gem, though the error was looking for the non-fingerprinted version.  Check and see if when you compile the assets - you get the fingerprinted versions placed in your public directory - and if you error says it is trying to find a non-fingerprinted version.  If this is the case (as it was mine), you can workaround this by placing the non-fingerprinted versions in the same targer folder where the fingerprinted-versions are found (my case /public/assets/font-awesome/ ) to at least temporarily work-around the broken asset pipeline? / gem? / css? issue.

**Comment by pooja-mane** [comment]
I have solved this issue by adding a line in application.css
*= require bootstrap_sb_admin_base_v2
*= require font-awesome
first we have to require bootstrap_sb_admin_base_v2 and then font-awesome.

**Comment by Virginia-Rucinski** [comment]
Just cleared this problem up with just adding the following into application.css:
*= require font-awesome

**Comment by Dote-x-e** [comment]
@Virginia-Rucinski Adding that only brought a sprockets file error on my side.

**Comment by jaydorsey** [comment]
I ran into another potential cause (and solution) for this error. If you're using one of the font-awesome gems, but also put the fontawesome.css file in your assets folder you might see this error. To fix it, remove the manually copied css file.
